# student name and AM:

Lemonaki Evangelia-Alkistis, 2554


# Quiz 1 - Part I - Regression 

\begin{exercise}
Describe the linear regression problem in symbolic form (using markdown and latex) assuming the data are subject to errors. What are the basic assumptions made? What is the form of **likelihood** function for this case? 
\end{exercise}

*********

In linear regression we have a function $$f(i) = \beta_0 + \beta_1*x_{i1} + ... + \beta_p*x_{ip} + \epsilon_i$$ and the parameters are the $\beta_i, i=0...p$ and $\epsilon_i$ is the error. We use ordinary least squares approach given a set of $(y_i,x_i)$ pairs. 

Data Assumption: $$\mathcal D = \{(x_1,y_1), (x_2,y_2), \dots, (x_n,y_n)\}\ y\_{i} \\in \\mathbb{R}\$$ and we calculate the weight vector $ w = [\beta_0, \beta_1,...,\beta_p]$ with $\beta_0 = 0$. 

Model Assumption:

* Each response generated by a linear model plus some Gaussian noise
\$y\_{i} = \\mathbf{w}\^\\top\\mathbf{x}\_i +
\\epsilon\_i\$ 

* Noise $\epsilon$ is drawn from a Gaussian distribution

\$\$\\epsilon\_i \\sim N(0, \\sigma\^2)\$\$

* Each response $y$ then becomes a draw from the following Gaussian:

\$\$\\Rightarrow y\_i|\\mathbf{x}\_i \\sim
N(\\mathbf{w}\^\\top\\mathbf{x}\_i, \\sigma\^2) \$\$

Likelihood function:

\$\$\\Rightarrow
P(y\_i|\\mathbf{x}\_i,\\mathbf{w})=\\frac{1}{\\sqrt{2\\pi\\sigma\^2}}e\^{-\\frac{(\\mathbf{x}\_i\^\\top\\mathbf{w}-y\_i)\^2}{2\\sigma\^2}}\$\$ and $\sigma$ is unknown, so it must be estimated.

In words, we assume that the data is drawn from a "line"  𝐰⊤𝐱  through the origin (one can always add a bias / offset through an additional dimension). For each data point with features  𝐱𝑖 , the label  𝑦  is drawn from a Gaussian with mean  𝐰⊤𝐱𝑖  and variance  𝜎2 . Our task is to estimate the weights (it is called slope in 1D case)  𝐰  from the data.

assume a fixed unknown mean and variance $\sigma^{2}$ corresponding to $y=\mu+\varepsilon$ regression model (here $\varepsilon$ is a zero mean and $\sigma^{2}$ variance):
$$
y \sim N\left(\mu, \sigma^{2}\right)
$$
$$
\mathcal{L}(\mu \mid y)=\prod_{i=1}^{n} P_{Y}\left(y_{i} \mid \mu, \sigma^{2}\right)=\prod_{i=1}^{n} \frac{1}{\sigma \sqrt{2 \pi}} e^{-\frac{\left(y_{i}-\mu\right)^{2}}{2 \sigma^{2}}}
$$

\begin{align}
\hat{\mu}=\arg \max _{\mu} \mathcal{L}(\mu \mid y) &=\arg \max _{\mu} \prod_{i=1}^{n} \frac{1}{\sigma \sqrt{2 \pi}} e^{-\frac{\left(y_{i}-\mu\right)}{2 \sigma^{2}}} \\
&=\arg \min _{\mu} \sum_{i=1}^{n}\left(y_{i}-\mu\right)^{2}
\end{align}

\begin{align}
\hat{\mu}=\arg \max _{\mu} \mathcal{L}(\mu \mid y) =\arg \max _{\mu} \prod_{i=1}^{n} \frac{1}{\sigma \sqrt{2 \pi}} e^{-\frac{\left(y_{i}-\mu\right)}{2 \sigma^{2}}}\\ 
=\arg \max _{\mu} \log \left(\prod_{i=1}^{n} \frac{1}{\sigma \sqrt{2 \pi}} e^{-\frac{\left(y_{i}-\mu\right)^{2}}{2 \sigma^{2}}}\right)\\
=\arg \max _{\mu} \sum_{i=1}^{n} \log \left(\frac{1}{\sigma \sqrt{2 \pi}}\right)+\log \left(e^{-\frac{\left(y_{i}-\mu\right)^{2}}{2 \sigma^{2}}}\right) \\
=\arg \max _{\mu} \sum_{i=1}^{n} \log \left(e^{-\frac{\left(y_{i}-\mu\right)^{2}}{2 \sigma^{2}}}\right)  
=\arg \min _{\mu} \sum_{i=1}^{n}\left(y_{i}-\mu\right)^{2}
\end{align}

\begin{array}{c}
\frac{\partial}{\partial \mu} \log \mathcal{L}(\mu \mid y)=0 \\
\frac{\partial}{\partial \mu} \sum_{i=1}^{n}\left(y_{i}-\mu\right)^{2}=0 \\
\sum_{i=1}^{n}-2\left(y_{i}-\mu\right)=0 \\
n \mu=\sum_{i=1}^{n} y_{i} \\
\mu=\frac{1}{n} \sum_{i=1}^{n} y_{i}
\end{array}

Finally, the expected value of $y$ is just the expected value of a normal distribution, which is just equal its mean:
$$
E(y)=\mu
$$
*******

\begin{exercise}
Assuming that $X$ is design matrix (given values for independent variables or features) and $y$ the vector values of the dependent variable or response, and the linear approximation of data is $y = Xw$ where the $w$ is the vector of unknown coefficients of the regression approximate function:

(i) formulate symbolically the optimization problem we must solve to find the OLS (ordinary least squares solution) 

(ii) formulate symbolically the optimization problem we must solve to find the Lasso approximation to the data. Explain its usefulness.

(iii)formulate symbolically the optimization problem we must solve to find the Ridge  approximation to the data. Explain its usefulness.

\end{exercise}


*******

(i) $$
\mathbf{W}=\underset{\mathbf{w}}{\operatorname{argmax}} P\left(y_{1}, \mathbf{x}_{1}, \ldots, y_{n}, \mathbf{x}_{n} \mid \mathbf{w}\right) \\
=\underset{\mathbf{w}}{\operatorname{argmin}} \frac{1}{n} \sum_{i=1}^n\left(\mathbf{x}_{i}^{\top} \mathbf{w}-y_{i}\right)^{2}
$$
We are minimizing a *loss function*, \$l(\\mathbf{w}) =
\\frac{1}{n}\\sum\_{i=1}\^n
(\\mathbf{x}\_i\^\\top\\mathbf{w}-y\_i)\^2\$. This loss function is called OLS.
-   Squared loss.
-   No regularization.
-   Closed form: \$\mathbf{w} = (\mathbf{X X\^\top})\^{-1}\mathbf{X}
    \mathbf{y}\^\top\$.
    
(ii)
-   \$\operatorname\*{min}\_{\mathbf{\mathbf{w}}}
    \frac{1}{n}\sum\_{i=1}\^n
    (\mathbf{x}\_i\^\top\mathbf{w}-y\_i)\^2 + \lambda
    |\mathbf{w}|$.

(iii) 
-   \$\operatorname\*{min}\_{\mathbf{\mathbf{w}}}
    \frac{1}{n}\sum\_{i=1}\^n
    (\mathbf{x}\_i\^\top\mathbf{w}-y\_i)\^2 + \lambda
    ||\mathbf{w}||\_2\^2\$.
-   Squared loss.
-   \$l2\text{-regularization}\$.
-   Closed form: \$\mathbf{w} = (\mathbf{X X\^{\top}}+\lambda
    \mathbf{I})\^{-1}\mathbf{X} \mathbf{y}\^\top\$.

\begin{exercise}
Apply the ridge regression (choose $\lambda = 0.01$) to the `Advertising.csv` dataset using  80% of the given data to train the model and predict the value of the response variable on the rest (20%) of data points. Measure the accuracy.  You can use the sklearn library.  

\end{exercise}


In [15]:
from pandas import read_csv
import matplotlib.pyplot as plt
from numpy import *
from sklearn import metrics
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

dataset = read_csv('advertising.csv')
print(dataset.head(3))
print(dataset.shape)
features = ['TV', 'Radio', 'Newspaper']
X = dataset[features]
y = dataset.Sales
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1)
#alpha is the lamba
ridgereg = Ridge(alpha=0.01, normalize=True)
ridgereg.fit(X_train, y_train)
y_pred = ridgereg.predict(X_test)
print (np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("Score:", ridgereg.score(X_test,y_test))
print(list (zip(features, ridgereg.coef_)))

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
(200, 4)
1.413400112785369
Score: 0.8924475589245054
[('TV', 0.04639297397141479), ('Radio', 0.17658368246831718), ('Newspaper', 0.003277002581042999)]


\begin{exercise}

(i) Describe  symbolically the solution of the regression problem using MLE (Maximum Likelihood Estimation) by specifying the associated optimization problem that you must solve. Apply this technique to solve numerically the above problem (`Advertizing.csv`) and describe the output you have obtain. You can use the sklearn library.

(ii) What is the main difference between the MLE and OLS methods? Notice that in sklearn the above method is referred as **gaussian_process**.

\end{exercise}


*****

(i) MLE is a technique used for estimating the parameters of a given s=distribution, using some observed data.MLE does that by finding particular values for the parameters (mean and variance) so that the resultant model with those parameters (mean and variance) would have generated the data. This is equivalent of solving the following optimization problem: $$
\mathbf{W}=\underset{\mathbf{w}}{\operatorname{argmax}} P\left(y_{1}, \mathbf{x}_{1}, \ldots, y_{n}, \mathbf{x}_{n} \mid \mathbf{w}\right) \\
=\underset{\mathbf{w}}{\operatorname{argmin}} \frac{1}{n} \sum_{i=1}\left(\mathbf{x}_{i}^{\top} \mathbf{w}-y_{i}\right)^{2}
$$

In [33]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor as GaussianProcess
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import DotProduct, WhiteKernel

kernel = DotProduct() + WhiteKernel()
dataset=pd.read_csv('advertising.csv')
X = dataset[features]
y = dataset.Sales
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1)
print(dataset.head(3))
gauss = GaussianProcess(kernel=kernel, random_state=0).fit(X_train, y_train)
y_pred = gauss.predict(X_test)
print (np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("Score:", gauss.score(X_test,y_test))

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
1.4123126737861804
Score: 0.8926129922308434


(ii) The ordinary least squares, or OLS, can also be called the linear least squares. This is a method for approximately determining the unknown parameters located in a linear regression model. It minimizes the square of the residuals.

Maximum likelihood estimation, or MLE, is a method used in estimating the parameters of a statistical model and for fitting a statistical model to data. It maximizes the probability of observing the dataset given a model and its parameters.

OLS: no assumption on the random error term of the linear model. 

MLE: random error is assumed to follow certain distribution (usually follow a normal distribution).

# Quiz 1 - Part II - Classification with Logistic Regression

\begin{exercise}

(i) In the binary classification problem assume that  the dataset for the independent variables is the matrix $X$ with dimensions $n \times p$  where $n$ indicates the number of data and $p$ the number of independent variables. The method tries to identify a boundary that separates the data points in two clusters. Indicate symbolically, in vector form, the equation of a linear boundary that separates the two clusters and specify the optimization problem that will determine this boundary.

(ii) Describe the logistic regression method symbolically utilizing the odds mathematical concept. 

(iii) Apply this method on the iris dataset (the design matrix or  values of independent variables). You can import the iris dataset using the following python statement:

        from sklearn.datasets import load_iris
        data = load_iris()

\end{exercise}


*****

(i) We have a decision boundary that separates the two classes. It is a line with type $y = b_0 + b_1*x_1+...$ $$ H_{\omega}(x) = g(\omega^T*x), g(z) = \frac{1}{1+e^{-z}} $$ So $$ h_{\omega}(x) = g(\omega + \omega*x_1 + \omega*x_2), \omega = [\omega_0 \omega_1 \omega_2]$$ 

Suppose that if $y=1$ and $\omega = [-3 ,1, 1]$ we have $ -3 + x_1 + x_2 \geq 0$ and $ x_1+x_2=3$ is the decision boundary.

(ii) When performing logistic regression we use $\pi = Pr(y=1|x) = \frac{e^{\beta_0+\beta_1x}}{1+e^{\beta_0+\beta_1x}}$, probability of y=1, given x. The logistic function takes on an “S” shape, where y is bounded by $[0,1]$. In order to interpret the outputs of a logistic function we must understand the difference between probability and odds. $$Odds = \frac{\pi}{1-\pi}$$ The odds of a logistic function is $\frac{\pi}{1-\pi} = \frac{\frac{e^{\beta_0+\beta_1x}}{1+e^{\beta_0+\beta_1x}}}{\frac{1-e^{\beta_0+\beta_1x}}{1+e^{\beta_0+\beta_1x}}} = e^{\beta_0+\beta_1x}$

If we take the logarithm of the odds, we get a linear equation $loag(\frac{\pi}{1-\pi}) = log(e^{\beta_0+\beta_1x}) = \beta_0+\beta_1x$

In logistc regression $\beta_1$ represents the change in the log-odds for a unit change in x. So, e^{\beta_1} gives the change in the odds for a unit in x.

(iii) 

In [72]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
iris_data = load_iris()
#print(iris_data.DESCR)
X, y = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names), pd.DataFrame(data=iris_data.target, columns=["iris_type"])
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
y_train, y_test = np.ravel(y_train), np.ravel(y_test)
logreg = LogisticRegression(random_state=0, solver='lbfgs', multi_class="multinomial", max_iter=400)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print (np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
logreg.score(X_test, y_test)

0.16222142113076254


0.9736842105263158

# Quiz 1 - Part III - PCA analysis of a toy problem

\begin{exercise}

Apply manually all the steps of PCA analysis in the following toy example

\end{exercise}


In [41]:
# Specify the input data

import numpy as np
X = np.array([[10,20,10],

              [2,5,2],

              [8,17,7],

              [9,20,10],

              [12,22,11]])

In [44]:
# output the data
print(X)
# specify the data as a matrix
X = np.matrix(X)
# compute the mean value of column of X
meanVals = np.mean(X, axis=0)
meanVals

[[10 20 10]
 [ 2  5  2]
 [ 8 17  7]
 [ 9 20 10]
 [12 22 11]]


matrix([[ 8.2, 16.8,  8. ]])

In [46]:
# Produce a zero-mean (centerd) version of X name it A
# A is the zero-mean (centered) version of X
# Produce the covariance matrix of X and print it
# C is the covarianvce matrix of X
# print (C)
# Note that the covariance C = (1/(N-1)) A.T*A
A = X - meanVals             # MC is the zero-mean (centered) version of X
CovM = np.cov(A, rowvar=0)    # CovM is the covarianvce matrix of M
print (np.dot(A.T,A)/(np.shape(X)[0]-1))

[[14.2  25.3  13.5 ]
 [25.3  46.7  24.75]
 [13.5  24.75 13.5 ]]


In [48]:
# Produce the eigenvalues and eigenvectors of the covariance matrix:
from numpy.linalg import eig
np.set_printoptions(precision=2,suppress=True)
# missing code
e, ev = eig(CovM)
print ("Eigenvalues:",e)
print ("Eigenvectors:",ev)

Eigenvalues: [73.72  0.38  0.3 ]
Eigenvectors: [[ 0.43  0.9  -0.04]
 [ 0.79 -0.41 -0.45]
 [ 0.42 -0.16  0.89]]


In [49]:
# Transform the full data into the new feature space based on the eigenvectors:
# missing code
newFeatures = ev[:,1].T
XTrans = np.dot(newFeatures, A.T)
print (XTrans.T)

[[ 0.  ]
 [ 0.17]
 [-0.1 ]
 [-0.9 ]
 [ 0.83]]


In [50]:
# Typically, we want a lower-dimensional space. We can sort the eigenvectors in the decreasing order of 
# their eigenvalues and take the top k. We'll take only the top first principal component 
#(since it has the largest eigenvalue, no sorting necessary):

reducedFeatures = ev[:,0].T

redcuedXTrans = np.dot(reducedFeatures, A.T)

print (redcuedXTrans.T)

[[  4.17]
 [-14.61]
 [ -0.35]
 [  3.74]
 [  7.05]]


In [52]:
# Use Scikit-learn decomposition module to do the same thing:
from sklearn import decomposition

# missing code
pca2 = decomposition.PCA(n_components=1)
XTrans2 = pca2.fit_transform(X)

print (XTrans2)

redcuedXTrans = XTrans2[:,0]

print (redcuedXTrans)

[[-4.17]
 [14.61]
 [ 0.35]
 [-3.74]
 [-7.05]]
[-4.17 14.61  0.35 -3.74 -7.05]


\begin{example}
An example of PCA analysis using sklearn library
\end{example}
 



In [2]:
#An example of using PCA for dimensionality reduction:
from numpy.linalg import eig
from sklearn.decomposition import PCA
import numpy as np

M = np.array([[2.5, 2.4],[0.5, 0.7], [2.2, 2.9],[1.9, 2.2],[3.1, 3.0],
[2.3, 2.7],[2, 1.6], [1, 1.1],[1.5, 1.6],[1.1, 0.9]])
meanM = np.mean(M, axis=0)
MC = M - meanM             # MC is the zero-mean (centered) version of X
CovM = np.cov(MC, rowvar=0)    # CovM is the covarianvce matrix of M
print ("Zero Mean Matrix:\n", MC,"\n")
print ("Covariance Matrix:\n", CovM,"\n")
eigVals, eigVecs = eig(CovM)
print ("Eigenvalues:\n", eigVals,"\n")
print ("Eigenvectors:\n", eigVecs,"\n")
newFeatures = eigVecs[:,1].T
MTrans = np.dot(newFeatures, MC.T)
print (np.mat(MTrans).T)
pca2 = PCA(n_components=1)
MTrans2 = pca2.fit_transform(M)
print (MTrans2)


Zero Mean Matrix:
 [[ 0.69  0.49]
 [-1.31 -1.21]
 [ 0.39  0.99]
 [ 0.09  0.29]
 [ 1.29  1.09]
 [ 0.49  0.79]
 [ 0.19 -0.31]
 [-0.81 -0.81]
 [-0.31 -0.31]
 [-0.71 -1.01]] 

Covariance Matrix:
 [[0.61655556 0.61544444]
 [0.61544444 0.71655556]] 

Eigenvalues:
 [0.0490834  1.28402771] 

Eigenvectors:
 [[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]] 

[[-0.82797019]
 [ 1.77758033]
 [-0.99219749]
 [-0.27421042]
 [-1.67580142]
 [-0.9129491 ]
 [ 0.09910944]
 [ 1.14457216]
 [ 0.43804614]
 [ 1.22382056]]
[[-0.82797019]
 [ 1.77758033]
 [-0.99219749]
 [-0.27421042]
 [-1.67580142]
 [-0.9129491 ]
 [ 0.09910944]
 [ 1.14457216]
 [ 0.43804614]
 [ 1.22382056]]


# Probabilistic Regression - Theory 

---
Linear Regression
---


### Assumptions

![](linreg.png) 

**Data Assumption**:

\$\mathcal D = \{(x_1,y_1), (x_2,y_2), \dots, (x_n,y_n)\}\$
\$y\_{i} \\in \\mathbb{R}\$

**Output**

We want to estimate the weight vector $\mathbf w$ of the linear regression model \$y\_{i} = \\mathbf{w}\^\\top\\mathbf{x}\_i +
\\epsilon\_i\$ 

**Model Assumption**: 

* Each response generated by a linear model plus some Gaussian noise
\$y\_{i} = \\mathbf{w}\^\\top\\mathbf{x}\_i +
\\epsilon\_i\$ 

* Noise $\epsilon$ is drawn from a Gaussian distribution

\$\$\\epsilon\_i \\sim N(0, \\sigma\^2)\$\$

* Each response y then becomes a draw from the following Gaussian:

\$\$\\Rightarrow y\_i|\\mathbf{x}\_i \\sim
N(\\mathbf{w}\^\\top\\mathbf{x}\_i, \\sigma\^2) \$\$

* Probability of each response variable is

\$\$\\Rightarrow
P(y\_i|\\mathbf{x}\_i,\\mathbf{w})=\\frac{1}{\\sqrt{2\\pi\\sigma\^2}}e\^{-\\frac{(\\mathbf{x}\_i\^\\top\\mathbf{w}-y\_i)\^2}{2\\sigma\^2}}\$\$ 
and it is called the **likelihood function**.

In words, we assume that the data is drawn from a "line"
\$\\mathbf{w}\^\\top \\mathbf{x}\$ through the origin (one can always
add a bias / offset through an additional dimension). For each data point with features
\$\\mathbf{x}\_i\$, the label \$y\$ is drawn from a Gaussian with mean
\$\\mathbf{w}\^\\top \\mathbf{x}\_i\$ and variance \$\\sigma\^2\$. Our
task is to estimate the slope \$\\mathbf{w}\$ from the data.

## Estimating with MLE (Maximum Likelihood Estimation) 

Maximum likelihood estimation (MLE) is a technique used for estimating the parameters of a given distribution, using some observed data. For example, if a population is known to follow a “normal distribution” but the “mean” and “variance” are unknown, MLE can be used to estimate them using a limited sample of the population. MLE does that by finding particular values for the parameters (mean and variance) so that the resultant model with those parameters (mean and variance) would have generated the data. This is equivalent of solving the following optimization problem:

\begin{equation}
\begin{aligned} \mathbf{w} &= 
\underset {\mathbf{w}} {argmax}
P(y_1,\mathbf{x}_1,...,y_n,\mathbf{x}_n|\mathbf{w})
\\ &=
\underset {\mathbf{w}} {argmax} \prod_{i=1}^n
P(y_i,\mathbf{x}_i|\mathbf{w}) & \textrm{(Because of
independence.)}
\\ &= 
\underset {\mathbf{w}} {argmax} \prod_{i=1}^n
P(y_i|\mathbf{x}_i,\mathbf{w})P(\mathbf{x}_i|\mathbf{w}) &
\textrm{(Chain rule of probability)}
\\ &=
\underset {\mathbf{w}} {argmax} \prod_{i=1}^n
P(y_i|\mathbf{x}_i,\mathbf{w})P(\mathbf{x}_i) &
\textrm{ ($\mathbf{x_i}$ is independent of $\mathbf{w_i}$)}
\\ &=
\underset {\mathbf{w}} {argmax} \prod_{i=1}^n
P(y_i|\mathbf{x}_i,\mathbf{w}) & 
\textrm{($P(\mathbf{x}_i)$ is
a constant - can be dropped.)}
\\ &=
\underset {\mathbf{w}} {argmax} \sum_{i=1}^n
\log [P(y_i|\mathbf{x}_i,\mathbf{w})] & 
\textrm{log is a monotonic function}
\\ &=
\underset {\mathbf{w}} {argmax} \sum_{i=1}^n
[ \log(\frac{1}{\sqrt{2\pi\sigma^2}}) +
\log (e^{-\frac{(\mathbf{x}_i^\top \mathbf{w}-y_i)^2}{2\sigma^2}})]
& \textrm{Plugging in probability distribution.}
\\ &=
\underset {\mathbf{w}} {argmax}
-\frac{1}{2\sigma^2}\sum_{i=1}^n
(\mathbf{x}_i^\top \mathbf{w}-y_i)^2 & 
\textrm{First term is a
constant, and $\log(e^z)=z$}
\\ &=
\underset {\mathbf{w}} {argmin}
\frac{1}{n}\sum_{i=1}^n (\mathbf{x}_i^\top\mathbf{w}-y_i)^2 &
\textrm{Always minimize; $\frac{1}{n}$ makes the loss interpretable
(average squared error).}
\end{aligned} 
\end{equation}


We are minimizing a *loss function*, \$l(\\mathbf{w}) =
\\frac{1}{n}\\sum\_{i=1}\^n
(\\mathbf{x}\_i\^\\top\\mathbf{w}-y\_i)\^2\$. This particular loss
function is also known as the squared loss or Ordinary Least Squares
(OLS). OLS can be optimized with gradient descent, Newton's method, or
in closed form.

**Closed Form:** 
$\mathbf{w} = (\mathbf{X}
\mathbf{X}^T)^{-1}\mathbf{X}\mathbf{y}^T$ where
$\mathbf{X}=[\mathbf{x}_1,\dots,\mathbf{x}_n]$
and $\mathbf{y}=[y_1,\dots,y_n]$.

\begin{remark}
Least Square Estimate is same as Maximum Likelihood Estimate under a Gaussian model ! 

\end{remark}


## Estimating with MAP (Maximum-a-Posteriori Estimation)

**What is MAP?**

The MAP criterion is derived from Bayes Rule, i.e.
\begin{equation}
	P(A \vert B) = \frac{P(B \vert A)P(A)}{P(B)} 
\end{equation}

If $B$ is chosen to be your data $\mathcal D$ and A is chosen to be the parameters that you'd want to estimate, call it $w$, you will get

\begin{equation}
	\underbrace{P(w \vert \mathcal{D})}_{\text{Posterior}} = 
	\frac{1}{\underbrace{P(\mathcal{D})}_{\text{Normalization}}}
\overbrace{P(\mathcal{D} \vert w)}^{\text{Likelihood}}\overbrace{P(w)}^{\text{Prior}}  \tag{0}
\end{equation}

In the case of regression 

\begin{equation}
	w \sim \mathcal{N}(0, \lambda^{-1}I)
\end{equation}
and 
\begin{equation}
	D \vert w \sim \mathcal{N}(w^T x, \sigma^2)
\end{equation}

## Deriving the Gaussian Prior 

Using the Normal distribution PDF with mean vector $\mu$ and covariance matrix $\Sigma$, which in the Multivariate case is

\begin{equation}
	f(x) = \frac{1}{\sqrt{(2\pi)^{N} \det \Sigma}}exp(-\frac{1}{2} (x - \mu)^T \Sigma^{-1} (x - \mu)) \tag{1}
\end{equation}

$w$  is a Normal with zero mean $\mu=0$ and variance $\Sigma=\lambda^1I$. Plug it in the above equation, you will get

\begin{equation}
	f(w) =  \frac{1}{\sqrt{(2\pi)^N \frac{1}{\lambda^D}}}exp(-\frac{1}{2}(w - 0)^T (\frac{1}{\lambda} I)^{-1} (w - 0))
\end{equation}

and 

\begin{equation}
	f(w) = \frac{\lambda^{\frac{N}{2}}}{(2\pi)^{\frac{N}{2}}}exp(-\frac{\lambda}{2} w^T w)
\end{equation}

**Deriving the Likelihood function**

From the above equation we get $f(\mathcal D|w)$ finding $f(y_k|w)$ with mean $w^\top x$ and variance $\sigma^2$, i.e.

\begin{equation}
	f(y_k \vert w) = \frac{1}{\sqrt{2\pi\sigma^2}}exp(-\frac{1}{2\sigma^2}(y_k- x^Tw)^2)
\end{equation}

But since $y_1 \ldots y_N$ are independent, then 

\begin{equation}
	f(\mathcal{D} \vert w) = f(y_1 \ldots y_N \vert w) = \prod_{k=1}^N f(y_k \vert w)
	=
	\prod_{k=1}^N  \frac{1}{\sqrt{2\pi\sigma^2}}exp(-\frac{1}{2\sigma^2}(y_k- x^Tw)^2)
\end{equation}





### Deriving the MAP criterion

\begin{exercise}
Show the following relations
\end{exercise}

**Additional Model Assumption**: \$P(\mathbf{w}) =
\frac{1}{\sqrt{2\pi\tau\^2}}e\^{-\frac{\mathbf{w}\^\top\mathbf{w}}{2\tau\^2}}\$\

\begin{equation}
\begin{aligned} \mathbf{w} &=
\underset {\mathbf{w}} {argmax}
P(\mathbf{w}|y_1,\mathbf{x}_1,...,y_n,\mathbf{x}_n)
\\ &=
\underset {\mathbf{w}} {argmax}
\frac{P(y_1,\mathbf{x}_1,...,y_n,\mathbf{x}_n|\mathbf{w})P(\mathbf{w})}{P(y_1,\mathbf{x}_1,...,y_n,\mathbf{x}_n)}
\\
&= \underset {\mathbf{w}} {argmax}
P(y_1,\mathbf{x}_1,...,y_n,\mathbf{x}_n|\mathbf{w})P(\mathbf{w})
\\
&= \underset {\mathbf{w}} {argmax}
\left[\prod_{i=1}^n P(y_i,\mathbf{x}_i|\mathbf{w})\right]P(\mathbf{w})
\\
&= \underset {\mathbf{w}} {argmax}
\left[\prod_{i=1}^nP(y_i|\mathbf{x}_i,\mathbf{w})P(\mathbf{x}_i|\mathbf{w})\right]P(\mathbf{w})
\\
&= \underset {\mathbf{w}} {argmax}
\left[\prod_{i=1}^nP(y_i|\mathbf{x}_i,\mathbf{w})P(\mathbf{x}_i)\right]P(\mathbf{w})
\\
&= \underset {\mathbf{w}} {argmax}
\left[\prod_{i=1}^n
P(y_i|\mathbf{x}_i,\mathbf{w})\right]P(\mathbf{w})
\\ &=
\underset {\mathbf{w}} {argmax} \sum_{i=1}^n 
\log P(y_i|\mathbf{x}_i,\mathbf{w})+ \log P(\mathbf{w})
\\ &=
\underset {\mathbf{w}} {argmax} -\left(\frac{1}{2\sigma^2}
\sum_{i=1}^n (\mathbf{x}_i^T\mathbf{w}-y_i)^2 +
\frac{1}{2\tau^2}\mathbf{w}^T\mathbf{w}\right)
\\ &=
\underset {\mathbf{w}} {argmin} \frac{1}{2\sigma^2}
\sum_{i=1}^n (\mathbf{x}_i^T\mathbf{w}-y_i)^2 +
\frac{1}{2\tau^2}\mathbf{w}^T\mathbf{w}
\\ &=
\underset {\mathbf{w}} {argmin} \frac{1}{n}
\sum_{i=1}^n (\mathbf{x}_i^T\mathbf{w}-y_i)^2 + \lambda||
\mathbf{w}||_2^2 & 
{\lambda=\frac{\sigma^2}{n\tau^2}} 
\end{aligned}
\end{equation}


This objective is known as Ridge Regression. It has a closed form
solution of: $\mathbf{w} = (\mathbf{X X}^T+\lambda
\mathbf{I})^{-1}\mathbf{X}\mathbf{y}^T$ where
$\mathbf{X}=[\mathbf{x}_1,\dots,\mathbf{x}_n]$
and $\mathbf{y}=[y_1,\dots,y_n]$.

**Relation between MAP and MLE**
If $w$ is not random, then Maximum Likelihood is MAP, why ? because $P(w)$ is 1, i.e. a distribution of a non-random term. 


### Summary

**Ordinary Least Squares:**

-   \$\underset {\mathbf{w}}{min}
    \frac{1}{n}\sum_{i=1}^n
    (\mathbf{x}_i^\top\mathbf{w}-y_i)^2$.
-   Squared loss.
-   No regularization.
-   Closed form: \$\mathbf{w} = (\mathbf{X X\^\top})\^{-1}\mathbf{X}
    \mathbf{y}\^\top\$.


**Ridge Regression:**

-   \$\operatorname\*{min}\_{\mathbf{\mathbf{w}}}
    \frac{1}{n}\sum\_{i=1}\^n
    (\mathbf{x}\_i\^\top\mathbf{w}-y\_i)\^2 + \lambda
    ||\mathbf{w}||\_2\^2\$.
-   Squared loss.
-   \$l2\text{-regularization}\$.
-   Closed form: \$\mathbf{w} = (\mathbf{X X\^{\top}}+\lambda
    \mathbf{I})\^{-1}\mathbf{X} \mathbf{y}\^\top\$.